spring.application.name=GestionBiblioteca
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_biblioteca
spring.datasource.username=root
spring.datasource.password=002731Salo@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Perfil activo
spring.profiles.active=dev

# Nombre de la aplicación
spring.application.name=GestionBiblioteca-ITM